version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      api-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/mcp-server"
    schedule:
      interval: "weekly"
    groups:
      mcp-server-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    groups:
      website-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
