sonar.organization=estanixx
sonar.projectKey=estanixx_cool-python-project
sonar.projectName=cool-python-project
sonar.sources=api/,mcp-server/
sonar.tests=api/tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/tests/**,**/vendor/**,**/node_modules/**
